//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInterface.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class components {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal components() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerInterface.Lang.components", typeof(components).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomme.
        /// </summary>
        internal static string apple {
            get {
                return ResourceManager.GetString("apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apples.
        /// </summary>
        internal static string apples {
            get {
                return ResourceManager.GetString("apples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacon.
        /// </summary>
        internal static string bacon {
            get {
                return ResourceManager.GetString("bacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beef.
        /// </summary>
        internal static string beef {
            get {
                return ResourceManager.GetString("beef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bread.
        /// </summary>
        internal static string bread {
            get {
                return ResourceManager.GetString("bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheese.
        /// </summary>
        internal static string cheese {
            get {
                return ResourceManager.GetString("cheese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken.
        /// </summary>
        internal static string chicken {
            get {
                return ResourceManager.GetString("chicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chips.
        /// </summary>
        internal static string chips {
            get {
                return ResourceManager.GetString("chips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        internal static string cookies {
            get {
                return ResourceManager.GetString("cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucumber.
        /// </summary>
        internal static string cucumber {
            get {
                return ResourceManager.GetString("cucumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucumbers.
        /// </summary>
        internal static string cucumbers {
            get {
                return ResourceManager.GetString("cucumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg.
        /// </summary>
        internal static string egg {
            get {
                return ResourceManager.GetString("egg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs.
        /// </summary>
        internal static string eggs {
            get {
                return ResourceManager.GetString("eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ham.
        /// </summary>
        internal static string ham {
            get {
                return ResourceManager.GetString("ham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string italian {
            get {
                return ResourceManager.GetString("italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettuce.
        /// </summary>
        internal static string lettuce {
            get {
                return ResourceManager.GetString("lettuce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayonnaise.
        /// </summary>
        internal static string mayonnaise {
            get {
                return ResourceManager.GetString("mayonnaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mustard.
        /// </summary>
        internal static string mustard {
            get {
                return ResourceManager.GetString("mustard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive.
        /// </summary>
        internal static string olive {
            get {
                return ResourceManager.GetString("olive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olives.
        /// </summary>
        internal static string olives {
            get {
                return ResourceManager.GetString("olives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onion.
        /// </summary>
        internal static string onion {
            get {
                return ResourceManager.GetString("onion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions.
        /// </summary>
        internal static string onions {
            get {
                return ResourceManager.GetString("onions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pepper.
        /// </summary>
        internal static string pepper {
            get {
                return ResourceManager.GetString("pepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pepperoni.
        /// </summary>
        internal static string pepperoni {
            get {
                return ResourceManager.GetString("pepperoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pepperonis.
        /// </summary>
        internal static string pepperonis {
            get {
                return ResourceManager.GetString("pepperonis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peppers.
        /// </summary>
        internal static string peppers {
            get {
                return ResourceManager.GetString("peppers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickles.
        /// </summary>
        internal static string pickles {
            get {
                return ResourceManager.GetString("pickles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranch.
        /// </summary>
        internal static string ranch {
            get {
                return ResourceManager.GetString("ranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salad.
        /// </summary>
        internal static string salad {
            get {
                return ResourceManager.GetString("salad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt.
        /// </summary>
        internal static string salt {
            get {
                return ResourceManager.GetString("salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauerkraut.
        /// </summary>
        internal static string sauerkraut {
            get {
                return ResourceManager.GetString("sauerkraut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach.
        /// </summary>
        internal static string spinach {
            get {
                return ResourceManager.GetString("spinach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steak.
        /// </summary>
        internal static string steak {
            get {
                return ResourceManager.GetString("steak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss.
        /// </summary>
        internal static string swiss {
            get {
                return ResourceManager.GetString("swiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        internal static string tomato {
            get {
                return ResourceManager.GetString("tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomatoes.
        /// </summary>
        internal static string tomatoes {
            get {
                return ResourceManager.GetString("tomatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuna.
        /// </summary>
        internal static string tuna {
            get {
                return ResourceManager.GetString("tuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        internal static string turkey {
            get {
                return ResourceManager.GetString("turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        internal static string wheat {
            get {
                return ResourceManager.GetString("wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
    }
}
