//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInterface.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerInterface.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number:.
        /// </summary>
        internal static string accountNumber {
            get {
                return ResourceManager.GetString("accountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bread.
        /// </summary>
        internal static string bread {
            get {
                return ResourceManager.GetString("bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string changesCat {
            get {
                return ResourceManager.GetString("changesCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as guest.
        /// </summary>
        internal static string continueAsGuest {
            get {
                return ResourceManager.GetString("continueAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create loyalty account.
        /// </summary>
        internal static string createLoyalty {
            get {
                return ResourceManager.GetString("createLoyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a Loyalty Card Click here.
        /// </summary>
        internal static string createLoyaltyBut {
            get {
                return ResourceManager.GetString("createLoyaltyBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string customizeBut {
            get {
                return ResourceManager.GetString("customizeBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        internal static string deserts {
            get {
                return ResourceManager.GetString("deserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts.
        /// </summary>
        internal static string desserts {
            get {
                return ResourceManager.GetString("desserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string drinks {
            get {
                return ResourceManager.GetString("drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in your account number:.
        /// </summary>
        internal static string enterAccountInfo {
            get {
                return ResourceManager.GetString("enterAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your information:.
        /// </summary>
        internal static string enterInfo {
            get {
                return ResourceManager.GetString("enterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Items.
        /// </summary>
        internal static string favoriteItems {
            get {
                return ResourceManager.GetString("favoriteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Order.
        /// </summary>
        internal static string finishOrderBut {
            get {
                return ResourceManager.GetString("finishOrderBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string itemCat {
            get {
                return ResourceManager.GetString("itemCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageTab {
            get {
                return ResourceManager.GetString("languageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Account.
        /// </summary>
        internal static string loyaltyTab {
            get {
                return ResourceManager.GetString("loyaltyTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menuTab {
            get {
                return ResourceManager.GetString("menuTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSA.
        /// </summary>
        internal static string NSAText {
            get {
                return ResourceManager.GetString("NSAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string orderTab {
            get {
                return ResourceManager.GetString("orderTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Total:.
        /// </summary>
        internal static string orderTotal {
            get {
                return ResourceManager.GetString("orderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Orders.
        /// </summary>
        internal static string pastOrders {
            get {
                return ResourceManager.GetString("pastOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string priceCat {
            get {
                return ResourceManager.GetString("priceCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string random {
            get {
                return ResourceManager.GetString("random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string removeBut {
            get {
                return ResourceManager.GetString("removeBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more orders for a free sandwich!.
        /// </summary>
        internal static string rewards {
            get {
                return ResourceManager.GetString("rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salad.
        /// </summary>
        internal static string salad {
            get {
                return ResourceManager.GetString("salad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandwich.
        /// </summary>
        internal static string sandwich {
            get {
                return ResourceManager.GetString("sandwich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Loyalty Card or Press Start.
        /// </summary>
        internal static string scanLoyaltyText {
            get {
                return ResourceManager.GetString("scanLoyaltyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        internal static string selectLangText {
            get {
                return ResourceManager.GetString("selectLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sides.
        /// </summary>
        internal static string sides {
            get {
                return ResourceManager.GetString("sides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign into loyalty account.
        /// </summary>
        internal static string signIntoLoyalty {
            get {
                return ResourceManager.GetString("signIntoLoyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Order.
        /// </summary>
        internal static string startOrderBut {
            get {
                return ResourceManager.GetString("startOrderBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
